-- ============================================================
-- SQL SCHEMA FOR SUPABASE DATABASE - EL PEDREGAL S.A.
-- Project ID: zicvanezsbmwgbporfps
-- ============================================================

-- Enable Row Level Security (RLS) if needed, or configure public access rules.

-- 1. Table: operarios
CREATE TABLE IF NOT EXISTS public.operarios (
    dni TEXT PRIMARY KEY,
    nombre_completo TEXT NOT NULL,
    fecha_registro TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT dni_length CHECK (char_length(dni) = 8)
);

-- Index on operarios name for quick autocomplete searches
CREATE INDEX IF NOT EXISTS idx_operarios_nombre ON public.operarios (nombre_completo);

-- 2. Table: supervisores
CREATE TABLE IF NOT EXISTS public.supervisores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    clave TEXT NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_registro TIMESTAMPTZ DEFAULT NOW()
);

-- Seed data for supervisores
INSERT INTO public.supervisores (nombre, clave, activo)
VALUES 
    ('Edwin', 'Edwin2025!', TRUE),
    ('Damian', 'Damian2025!', TRUE),
    ('Demetrio', 'Demetrio2025!', TRUE),
    ('Gerardo', 'Gerardo2025!', TRUE)
ON CONFLICT (nombre) DO UPDATE 
SET clave = EXCLUDED.clave, activo = EXCLUDED.activo;

-- 3. Table: asistencia
CREATE TABLE IF NOT EXISTS public.asistencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TEXT NOT NULL, -- Format: dd/MM/yyyy
    dni TEXT NOT NULL,
    nombre TEXT NOT NULL,
    supervisor TEXT NOT NULL,
    estado TEXT NOT NULL CHECK (estado IN ('Trabajo', 'Descanso', 'Falta')),
    codigo_labor TEXT,
    lote TEXT,
    hora_inicio TEXT, -- Format: HH:mm
    hora_fin TEXT,    -- Format: HH:mm
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_operarios FOREIGN KEY (dni) REFERENCES public.operarios(dni) ON DELETE CASCADE
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_asistencia_fecha ON public.asistencia (fecha);
CREATE INDEX IF NOT EXISTS idx_asistencia_supervisor_fecha ON public.asistencia (supervisor, fecha);
CREATE INDEX IF NOT EXISTS idx_asistencia_dni_fecha ON public.asistencia (dni, fecha);

-- 4. Table: historial
CREATE TABLE IF NOT EXISTS public.historial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni TEXT NOT NULL,
    nombre TEXT NOT NULL,
    supervisor TEXT NOT NULL,
    primera_vez TIMESTAMPTZ DEFAULT NOW(),
    ultima_vez TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_dni_supervisor UNIQUE (dni, supervisor)
);

-- Enable full read/write access for anonymized/authenticated requests on public schema
-- (or configure your RLS policies on the Supabase dashboard)
ALTER TABLE public.operarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supervisores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asistencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historial ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read and write access" ON public.operarios FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read and write access" ON public.supervisores FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read and write access" ON public.asistencia FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read and write access" ON public.historial FOR ALL USING (true) WITH CHECK (true);

-- 5. Table: reloj (Carga Reloj)
CREATE TABLE IF NOT EXISTS public.reloj (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TEXT NOT NULL, -- Format: dd/MM/yyyy
    dni TEXT NOT NULL,
    nombre TEXT,
    entrada TEXT, -- Format: HH:mm
    salida TEXT,  -- Format: HH:mm
    horas NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_reloj_dni_fecha UNIQUE (dni, fecha)
);

CREATE INDEX IF NOT EXISTS idx_reloj_fecha ON public.reloj (fecha);
CREATE INDEX IF NOT EXISTS idx_reloj_dni_fecha ON public.reloj (dni, fecha);

ALTER TABLE public.reloj ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read and write access" ON public.reloj FOR ALL USING (true) WITH CHECK (true);

-- 6. Table: trabajadores_supervisor
CREATE TABLE IF NOT EXISTS public.trabajadores_supervisor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supervisor_key TEXT NOT NULL,
    dni TEXT NOT NULL,
    nombre TEXT NOT NULL
);

ALTER TABLE public.trabajadores_supervisor ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read and write access" ON public.trabajadores_supervisor FOR ALL USING (true) WITH CHECK (true);


